### ISSUE TITLE
Bug - invalid zipcode

### ISSUE THREAD

**Issue by rgraue** [climate-cooperative/home-energy-calculator#41]
## Description

When an invalid zipcode is entered, it is possible to continue through the calculator, even though the zipcode data returned will error out on the results page.

## Technical Notes

- add validation to /zipcode page
- add validation to results page. Maybe an error page? or component
- don't use window local storage... we already use react's context functionality

## Risks

none

## Related Issues Or Discussions

#29 #30

**Comment by codeexpert74** [comment]
I want to know about the zipcode verification pipeline in detail.
